# 主配置
debug: true
lightning: true

# 1.7.10 适配配置（移除 title-settings 部分）
version-specific:
  1_7_10:
    use-command-title: true
    title-command: "iu title {player} {title} {subtitle}"  # 你的命令格式
    sound-mappings:
      ENDERDRAGON_GROWL: "ENDERDRAGON_WINGS"
      LEVEL_UP: "LEVEL_UP"

# VIP 特效配置
viptitle:
  vip1:
    title: "&6欢迎 &a{player}"
    subtitle: "&7享受 VIP 特权"
    sound: "ENDERDRAGON_GROWL"
  vip2:
    title: "&e尊贵 &a{player}"
    subtitle: "&7您的特权更高"
    sound: "FIREWORK_LAUNCH"

# 普通欢迎消息
normalJoinMessage:
  enabled: true
  messages:
    - "&e欢迎 {player} 加入服务器！"
    - "&7请遵守规则"